theme = "modern"
icons = "awesome"

[[block]]
block = "custom"
cycle = ["xrandr -s 1920x1080", "xrandr -s 1600x900"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB ({Mup}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "ens3"
ssid = true
ip = false
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m.%Y %H:%M"
on_click = "gsimplecal &"

#[[block]]
#block = "battery"