theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "custom"
json = true
cycle = ['''echo "{\"icon\":\"ping\",\"text\":\"`xrandr -s 1920x1080`\"}"''', '''echo "{\"icon\":\"ping\",\"text\":\"`xrandr -s 1600x900`\"}"''']

[[block]]
block = "disk_space"
path = "/"
alias = "/"
format = "{icon} {used}/{total}"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "ens3"
#format = "{ssid} {signal_strength} {speed_up;K*b} {speed_down;K*b}"
format = "{speed_up;K*b} {speed_down;K*b}"
interval = 5

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m.%Y %H:%M"
on_click = "gsimplecal &"

#[[block]]
#block = "battery"